### ISSUE TITLE
Add wall-breaker with random spawn

### ISSUE THREAD

**Issue by rowan04** [rowan04/CW3-Maze-Game#11]
Add wall breaker that spawns randomly in different spawn points across the maze.
Will be able to break one wall piece, allowing the user to break into the exit.

Maybe add a feature in which if the player accidentally uses their wall breaker not on the exit, another one will spawn? So that the player can't get stuck.

**Comment by rowan04** [comment]
as mentioned on excel sheet

**Comment by Will-Cross1** [comment]
could make it so there is something in all possible spawn locations

- wall breaker
- potion
- score increaser

**Comment by Will-Cross1** [comment]
time stop potion?


could make add items a different issue

**Comment by rowan04** [comment]
> could make it so there is something in all possible spawn locations
> 
> * wall breaker
> * potion
> * score increaser

yeah ok

**Comment by rowan04** [comment]
> b ut the wall breaker is only in 1 of the spaces

yh

**Comment by Will-Cross1** [comment]
can only see item line of sight?
or when a few blocks apart from it?

**Comment by rowan04** [comment]
> can only see item line of sight? or when a few blocks apart from it?

no i think a few blocks apart from it

**Comment by rowan04** [comment]
> > can only see item line of sight? or when a few blocks apart from it?
> 
> no i think a few blocks apart from it

like within a y coord and x coord range of it, maybe 75

**Comment by rowan04** [comment]
btw i have implemented the random spawn, havent done the rest of it yet
