### ISSUE TITLE
pressing enter resets the maze

### ISSUE THREAD

**Issue by rowan04** [rowan04/CW3-Maze-Game#32]
pressing enter resets the maze

sorta cool but probably shouldnt happen.
easy to do accidentally

**Comment by rowan04** [comment]
> issue in MyWorld public void act()
> 
> the if statement in it can always be activated
> 
> figure out way for intro screen to disappear without using that method

also, if you click enter on the death screen, the text all stays on screen, and the maze put back on top of it

**Comment by Will-Cross1** [comment]
currently this is quite convenient for testing

**Comment by rowan04** [comment]
> currently this is quite convenient for testing

agreed

**Comment by Will-Cross1** [comment]
Im going to make it so that it stays but when you press enter it fully resets it so its easier to restart

**Comment by rowan04** [comment]
> Im going to make it so that it stays but when you press enter it fully resets it so its easier to restart

ok

**Comment by Will-Cross1** [comment]
#72
