### ISSUE TITLE
overhaul images

### ISSUE THREAD

**Issue by rowan04** [rowan04/CW3-Maze-Game#33]
Change all the images to make it look better

**Comment by rowan04** [comment]
this issue has been started with the retexturing of the walls, implemented in #59

**Comment by Will-Cross1** [comment]
- [ ] background
- [ ] start
- [ ] end
- [ ] time freeze
- [ ] wall breaker
- [ ] teleport

**Comment by Will-Cross1** [comment]
to make the hotbox more obvious could make it a fat stick figure? (or heavy armour?)

**Comment by rowan04** [comment]
> to make the hotbox more obvious could make it a fat stick figure? (or heavy armour?)

the way ill make the image, the hitbox will be the player, there wont be any white space on the side

**Comment by rowan04** [comment]
are we happy with the ghost image?

**Comment by Will-Cross1** [comment]
if you are

**Comment by rowan04** [comment]
> * [x]  walls [Revamp walls #59](https://github.com/rowan04/CW3-Maze-Game/pull/59)
> * [x]  breakable walls [Update breakable wall texture #63](https://github.com/rowan04/CW3-Maze-Game/pull/63)
> * [x]  background [Changing background to grey #65](https://github.com/rowan04/CW3-Maze-Game/pull/65)
> * [x]  start [Update start image #85](https://github.com/rowan04/CW3-Maze-Game/pull/85)
> * [x]  end [Add new end-portal image #69](https://github.com/rowan04/CW3-Maze-Game/pull/69)
> * [x]  time freeze [Update time-freeze image #91](https://github.com/rowan04/CW3-Maze-Game/pull/91)
> * [x]  wall breaker [Update wallbreaker image #75](https://github.com/rowan04/CW3-Maze-Game/pull/75)
> * [x]  teleport [Update teleporter image #92](https://github.com/rowan04/CW3-Maze-Game/pull/92)
> * [x]  treasure [Add treasure image #90](https://github.com/rowan04/CW3-Maze-Game/pull/90)
> * [x]  trophy (accidentally pushed to main)
> * [x]  player [Update player image #94](https://github.com/rowan04/CW3-Maze-Game/pull/94)
> * [x]  ghost [Adding coloured ghosts #87](https://github.com/rowan04/CW3-Maze-Game/pull/87)
> * [x]  magnet [Update magnet image #89](https://github.com/rowan04/CW3-Maze-Game/pull/89)
> * [x]  zapper [Update zapper image #88](https://github.com/rowan04/CW3-Maze-Game/pull/88)

all done :)
