### ISSUE TITLE
teleport to home item

### ISSUE THREAD

**Issue by Will-Cross1** [rowan04/CW3-Maze-Game#41]

**Comment by rowan04** [comment]
whats the plan for this? how would it work?

**Comment by Will-Cross1** [comment]
pickup item that could either teleport you back to the start if you are killed or teleport you back to the start if you press a number

**Comment by rowan04** [comment]
> pickup item that could either teleport you back to the start if you are killed or teleport you back to the start if you press a number

ok

**Comment by Will-Cross1** [comment]
done
