### ISSUE TITLE
Add more functionality to player (inventory + other items?)

### ISSUE THREAD

**Issue by rowan04** [rowan04/CW3-Maze-Game#8]
Give player more functionality
- inventory?
- ability to use items?
- other

**Comment by Will-Cross1** [comment]
could use numbers when an item is picked up

**Comment by rowan04** [comment]
> Like have a row on the bottom of the screen with the options and if you collected an item then you can press like 2 or something to use it

yeah sure

**Comment by Will-Cross1** [comment]
need to add those items in first

**Comment by rowan04** [comment]
Imma close this issue, and we'll make more specific ones for new items and such
