### ISSUE TITLE
add difficulty?

### ISSUE THREAD

**Issue by Will-Cross1** [rowan04/CW3-Maze-Game#83]
before maze starts have difficulty choice

different numbers of ghosts?
different ghost speeds?

varying points per difficulty?

**Comment by rowan04** [comment]
i dont think it should change the number of ghosts - they were carefully placed to prevent clear runs to the end

**Comment by Will-Cross1** [comment]
but its so hard :(


im making an optional difficulty right now that the player can choose

**Comment by Will-Cross1** [comment]
hard (what it is now)
medium (slower ghosts)
easy (slower ghosts and 1 less ghost)

**Comment by rowan04** [comment]
which ghost is going

**Comment by rowan04** [comment]
i dont think its that hard to get the wallbreaker and get to the end, when you're going for highest score possible then yes it is

**Comment by rowan04** [comment]
well it is hard but its not too challenging

**Comment by rowan04** [comment]
and it shouldnt be easy

**Comment by Will-Cross1** [comment]
#84
